# Show when a loot table is cleared from a chest in the console/log
show-cleared-loot-tables: true

# Add loot tables to this list to have them
# cleared from chests when they are opened
clear-loot-tables-on-use:
- "minecraft:chests/example"
